-- AlterTable
ALTER TABLE "Car" ADD COLUMN "braids" TEXT;
ALTER TABLE "Car" ADD COLUMN "chassis" TEXT;
ALTER TABLE "Car" ADD COLUMN "frontTrackMm" REAL;
ALTER TABLE "Car" ADD COLUMN "gearRatio" TEXT;
ALTER TABLE "Car" ADD COLUMN "groundClearanceMm" REAL;
ALTER TABLE "Car" ADD COLUMN "guide" TEXT;
ALTER TABLE "Car" ADD COLUMN "lengthMm" REAL;
ALTER TABLE "Car" ADD COLUMN "magnet" TEXT;
ALTER TABLE "Car" ADD COLUMN "motor" TEXT;
ALTER TABLE "Car" ADD COLUMN "notes" TEXT;
ALTER TABLE "Car" ADD COLUMN "rearTrackMm" REAL;
ALTER TABLE "Car" ADD COLUMN "scale" TEXT;
ALTER TABLE "Car" ADD COLUMN "tyresFront" TEXT;
ALTER TABLE "Car" ADD COLUMN "tyresRear" TEXT;
ALTER TABLE "Car" ADD COLUMN "weightGrams" INTEGER;
ALTER TABLE "Car" ADD COLUMN "wheelbaseMm" REAL;
ALTER TABLE "Car" ADD COLUMN "widthMm" REAL;
